### ISSUE TITLE
E-invoice information not get in vouchers

### ISSUE THREAD

**Issue by sunilsoni761** [Accounting-Companion/TallyConnector#12]
Dear sir please added E-invoice information in vouchers class

**Comment by saivineeth100** [comment]
I will add, but It will take **some Time**
Now I am working on **Validation** and adding **new fields** for **Masters**
After **completing all Masters** I will start working on Vouchers

**Comment by sunilsoni761** [comment]
dear sir its possible for any update in tally prime than automatically update / notified

**Comment by saivineeth100** [comment]
I didn't Understand, What you are saying
Can you explain more clearly

**Comment by sunilsoni761** [comment]
Dear sir i have use tally prime and with connect with my c# application and i will create any voucher post from c# application to tally and my employees will change the voucher’s valve in tally prime so can i automatically update / notifications get from tally to c# application its possible or not

**Comment by saivineeth100** [comment]
You will not get automatic notifications like that
but you can implement this from Application Side 
you need to maintain some database for c# application and compare data with Tally and database at specific interval,
If any voucher is not matching as per local database then it is edited in Tally

**Comment by saivineeth100** [comment]
Hello @sunilsoni761 
Can you provide Some **Sample tally data with E-invoice information** to contact@saivineeth.com
