### ISSUE TITLE
Create company 

### ISSUE THREAD

**Issue by SakshamGairola** [Accounting-Companion/TallyConnector#15]
Hello,
Is there any way to create a Company through this API?

**Comment by saivineeth100** [comment]
**No**
This library uses Tally XML API
we cannot create company using Tally XML API (as per my knowledge)
If you know how to to create a company using XML API share here , I will implement in this Library

**Comment by SakshamGairola** [comment]
Thanks for your response i was just wondering if you can do that using the XML API but apprently not
