### ISSUE TITLE
Get All vouchers

### ISSUE THREAD

**Issue by pmsudhi** [Accounting-Companion/TallyConnector#17]
How do I get all vouchers?

**Comment by saivineeth100** [comment]
To Get All Vouchers from tally use below method
```C#
//Gets all vouchers from active company
List<Voucher> vouchers = tally.GetObjectsfromTally<Voucher>()
//you can pass optional params to get vouchers from specific company or specific period
List<Voucher> vouchers = tally.GetObjectsfromTally<Voucher>("companyname","fromdate","todate")

```

Refer [this link ](https://github.com/Accounting-Companion/TallyConnector/blob/159f18e862f3b65c59b7310d12ee0b04385bbf70/TallyConnector/Tally.cs#L408)to known what parameters are accepted

**Comment by pmsudhi** [comment]
Thanks for the quick update.
