### ISSUE TITLE
Hello Sir Can you show Basic Hello World Application using "TallyConnector"

### ISSUE THREAD

**Issue by chandansomani** [Accounting-Companion/TallyConnector#18]
Need a Beginners guide Video Tutorial to start using Tally Connector
One Application to start from

**Comment by saivineeth100** [comment]
I planned to create a full video series, you can see status at - https://github.com/orgs/Accounting-Companion/projects/3
YouTube Link - [Playlist](https://youtube.com/playlist?list=PLXk2wj8z1UsWQ1miKLvjv9ZfsioH88rnH)  
To get notified when videos are uploaded subscribe to [channel](https://www.youtube.com/channel/UCUQA0JZGgvS9-ZicVwpQBhA/)
Source Code is available at [repo](https://github.com/Accounting-Companion/TallyConnector_Samples)
![image](https://user-images.githubusercontent.com/64919520/175802945-f6ede491-0b76-4d5e-8f40-59c7b1973ba6.png)

**Comment by chandansomani** [comment]
No Video in playlist , & It is python based, 

any Connectivity tutorial for C# ?

**Comment by saivineeth100** [comment]
Still videos are not published 
I given project link , where you can track status of videos
I shared playlist link of C# tutorials only
