### ISSUE TITLE
Get stock quantity for a stock item

### ISSUE THREAD

**Issue by SpideySaif** [Accounting-Companion/TallyConnector#19]
Is it possible to get the available stock quantity for a particular stock item?

Thanks.

**Comment by saivineeth100** [comment]
Yes(we need to extend Stock Item Model for that)
I removed closing balances from all models as it can be **calculated**
If you wat to get closing balance or any field that is not there in default models you can extend that model and add that properties with correct XML Tag
In your case 
Stock Item Closing Balance is divided into 3 properties Closing Balance, Closing Value, Closing Rate
```C#
[XmlRoot(ElementName = "STOCKITEM")]
[XmlType(AnonymousType = true)]
public class StockItem : StockItem 
{
    [XmlElement(ElementName = "CLOSINGBALANCE")]
    public TallyQuantity? ClosingBal { get; set; }

    [XmlElement(ElementName = "CLOSINGVALUE")]
    public TallyAmount? ClosingValue { get; set; }

    [XmlElement(ElementName = "CLOSINGRATE")]
    public TallyRate? ClosingRate { get; set; }
}
#Make sure You use above type in GetStockItem<type>()
#Since Closingvalues not fetched automatically we need to explicitly specify in fetch list and send them as parameter
List<string> fetchList = new() { "MasterId", "CanDelete", "ClosingBalance", "ClosingRate", "ClosingValue", "*" };
StockItem  TallystockItem = tally.GetStockItem<StockItem>("name of StckItm", fetchList: fetchList);
# If you want closing bal at specified date then you need to send both from and to date parameters
StockItem TallystockItem = await Tally.GetStockItem<StockItem>("name of StckItm",fromDate: new DateTime(2006, 4, 1), toDate:new DateTime(2016,5,31), fetchList: fetchList);

# TallystockItem.ClosingBal  will have closingBal

```

**Comment by SpideySaif** [comment]
Can we get the closing details through XML request for a stock item?

**Comment by saivineeth100** [comment]
> Can we get the closing details through XML request for a stock item?

If you any issue regarding this library raise a issue here,
else use forums like stackoverflow
I added postman collection in [other useful resources ](https://github.com/Accounting-Companion/TallyConnector#other-useful-resources-related-to-tally-integration) there you can find all XMLS

**Comment by SpideySaif** [comment]
> Yes(we need to extend Stock Item Model for that) I removed closing balances from all models as it can be **calculated** If you wat to get closing balance or any field that is not there in default models you can extend that model and add that properties with correct XML Tag In your case Stock Item Closing Balance is divided into 3 properties Closing Balance, Closing Value, Closing Rate
> 
> ```cs
> [XmlRoot(ElementName = "STOCKITEM")]
> [XmlType(AnonymousType = true)]
> public class StockItem : StockItem 
> {
>     [XmlElement(ElementName = "CLOSINGBALANCE")]
>     public TallyQuantity? ClosingBal { get; set; }
> 
>     [XmlElement(ElementName = "CLOSINGVALUE")]
>     public TallyAmount? ClosingValue { get; set; }
> 
>     [XmlElement(ElementName = "CLOSINGRATE")]
>     public TallyRate? ClosingRate { get; set; }
> }
> #Make sure You use above type in GetStockItem<type>()
> StockItem  TallystockItem = tally.GetStockItem<StockItem>("name of StckItm");
> # TallystockItem.ClosingBal  will have closingBal
> ```

I tried getting this data through your library(which is great btw) by extending the StockItem model as you said, but I am getting errors on TallyQuantity and TallyRate as their references could not be found.

**Comment by saivineeth100** [comment]
You need to import relevant namespaces
TallyQuantity  and TallyRate  are in TallyConnector.Core.Converters.XMLConverterHelpers;
if TallyConnector.Core.Converters.XMLConverterHelpers is not there update TallyConnector package to latest version 1.0.8

**Comment by SpideySaif** [comment]
Yup.. updating to 1.0.8 solved the namespace issue. Now I am getting the ClosingBal, ClosingValue, ClosingRate as null but getting the values for same item if I check it through a xml request in postman.

**Comment by saivineeth100** [comment]
> Yes(we need to extend Stock Item Model for that) I removed closing balances from all models as it can be **calculated** If you wat to get closing balance or any field that is not there in default models you can extend that model and add that properties with correct XML Tag In your case Stock Item Closing Balance is divided into 3 properties Closing Balance, Closing Value, Closing Rate
> 
> ```cs
> [XmlRoot(ElementName = "STOCKITEM")]
> [XmlType(AnonymousType = true)]
> public class StockItem : StockItem 
> {
>     [XmlElement(ElementName = "CLOSINGBALANCE")]
>     public TallyQuantity? ClosingBal { get; set; }
> 
>     [XmlElement(ElementName = "CLOSINGVALUE")]
>     public TallyAmount? ClosingValue { get; set; }
> 
>     [XmlElement(ElementName = "CLOSINGRATE")]
>     public TallyRate? ClosingRate { get; set; }
> }
> #Make sure You use above type in GetStockItem<type>()
> #Since Closingvalues not fetched automatically we need to explicitly specify in fetch list and send them as parameter
> List<string> fetchList = new() { "MasterId", "CanDelete", "ClosingBalance", "ClosingRate", "ClosingValue", "*" };
> StockItem  TallystockItem = tally.GetStockItem<StockItem>("name of StckItm", fetchList: fetchList);
> # If you want closing bal at specified date then you need to send both from and to date parameters
> StockItem TallystockItem = await Tally.GetStockItem<StockItem>("name of StckItm",fromDate: new DateTime(2006, 4, 1), toDate:new DateTime(2016,5,31), fetchList: fetchList);
> 
> # TallystockItem.ClosingBal  will have closingBal
> ```

I updated previous code (Added Ex: to get closing balance on specific date)
Closing bal ,rate, value are not calculated by tally by default , if we want them we need to explicitly specify them in fetch list an d send to tally

**Comment by SpideySaif** [comment]
Worked like a charm. Thank you for your help.

**Comment by saivineeth100** [comment]
> Worked like a charm. Thank you for your help.

I am creating a Tutorial Series on Tally Connector
You can see Status at - [Project](https://github.com/orgs/Accounting-Companion/projects/3/views/1)

- [Video Tutorials ](https://youtube.com/playlist?list=PLXk2wj8z1UsWQ1miKLvjv9ZfsioH88rnH)
- [Blog Tutorials ](https://blog.accountingcompanion.com/)
You can follow there for fully understanding Tally Connector and its usage

**Don't forget to Start this Repo**

**Comment by sanketgroup** [comment]
What is the best way to get list of **_ALL_** stock items with closing Balance for a given date?
(Total Stock Items are around 15,000)

**Comment by saivineeth100** [comment]
I added [new method](https://github.com/Accounting-Companion/TallyConnector/blob/677e1e63932cc4c58ddb98ef7774f1504acbb284/src/TallyConnector/Services/TallyService/Main.cs#L247) to get large data from Tally
Which will fetch data in a paginated manner, so you no need to worry about
```cs
var StockItems= await _tallyService.GetAllObjectsAsync<StockItem>()
```

**This update is not released yet; you can enable include-pre-release to get this update**
