### ISSUE TITLE
C# code issue - DLL reference 

### ISSUE THREAD

**Issue by sanketgroup** [Accounting-Companion/TallyConnector#2]
Hello,
I did the following code in C#, just to start with basics.
I get errors as shown in screenshots.
Pls help.
Thanks
![image](https://user-images.githubusercontent.com/6008084/123095115-53e3b600-d44b-11eb-9aa8-0ebd0bc5862f.png)

**Comment by saivineeth100** [comment]
**mistakes from your side**
- You need wrap await tasks with async or else add .wait() at end
- you cannot put public fields inside private methods
- Replace voucher number and date with actual data

**1 mistake from documentation**

- public Tally Ctally = new Tally();

So your code should be
 
```C#
        public Tally Ctally = new Tally();
        private void Form2_Load(object sender, EventArgs e)
        {
            TallyInit();
        }
        private async void TallyInit()
        {
            string VoucherNumber = "vchnum";
            string Date = "somedate";
            string VoucherMasterID = "vchmasterid";
            Voucher voucher = await Ctally.GetVoucherByVoucherNumber(VoucherNumber, Date);
            //If you have master id of voucher
            Voucher voucher2 = await Ctally.GetVoucherByMasterID(VoucherMasterID);
        }
```
You need to add break point at voucher  and voucher2 to see data
![image](https://user-images.githubusercontent.com/64919520/123102136-60b7d800-d452-11eb-877f-ac2b60a8681d.png)

**Comment by sanketgroup** [comment]
I might be wrong given less experience with C#.
Following what I did, but not working.
```
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TallyConnector;
using TallyConnector.Models;

namespace tallytest
{
    public Tally Ctally = new Tally();
    private void Form2_Load(object sender, EventArgs e)
    {
        TallyInit();
    }
    private async void TallyInit()
    {
        string VoucherNumber = "vchnum";
        string Date = "somedate";
        string VoucherMasterID = "vchmasterid";
        Voucher voucher = await Ctally.GetVoucherByVoucherNumber("JV263", "20210331");
        //If you have master id of voucher
        Voucher voucher2 = await Ctally.GetVoucherByMasterID(VoucherMasterID);
    }
```

![image](https://user-images.githubusercontent.com/6008084/123139142-830e1d80-d473-11eb-8dbc-f0cf2decada4.png)

**Comment by saivineeth100** [comment]
You removed class definition

```C#
namespace tallytest
{
   Public partial class Form2:Form
  {
     //Code goes here
   }
}
```

**Comment by sanketgroup** [comment]
Getting following issue

![capture2](https://user-images.githubusercontent.com/6008084/123201732-e7ab9580-d4d0-11eb-9234-907f57b8fe2b.JPG)

**Comment by saivineeth100** [comment]
Try this
Replace 
```c#
using System.Windows.Forms;
```
with
```c#
using WF = System.Windows.Forms;
```
Form with
WF.Form

**Comment by sanketgroup** [comment]
Getting error in program.cs when clicking on button.
![image](https://user-images.githubusercontent.com/6008084/123211258-d23e6780-d4e0-11eb-83ad-015bed9c39c1.png)

![image](https://user-images.githubusercontent.com/6008084/123211268-d5395800-d4e0-11eb-8df4-9e3b014e60fc.png)

**Comment by sanketgroup** [comment]
![image](https://user-images.githubusercontent.com/6008084/123211740-7a543080-d4e1-11eb-89f9-3248c72bad61.png)

**Comment by saivineeth100** [comment]
Compare your previous code and this code - You will know
you Removed

```c#
public Form1(){
InitializeComponent();
}

**Comment by saivineeth100** [comment]
@sanketgroup  I added WPF example to the repo you can check now

**Comment by sanketgroup** [comment]
> Compare your previous code and this code - You will know
> you Removed
> 
> ```cs
> public Form1(){
> InitializeComponent();
> }
> ```

 **It gives error when I keep that .. Screenshot attached in previous post.**
**Posting again.**

===================


![image](https://user-images.githubusercontent.com/6008084/123215400-0405fd00-d4e6-11eb-9e02-d905344e8d11.png)

**Comment by saivineeth100** [comment]
Create a new windows forms application and try

**Comment by sanketgroup** [comment]
> Create a new windows forms application and try

I did that way, but the same error.

Also Could you please add an example project for .Net framework? ( i see only .Net core)

**Comment by saivineeth100** [comment]
example works for both(c#)

Also added WinForms example check

**Comment by sanketgroup** [comment]
while building your example, getting this error may be due to .Net5.0 core, which I do not have.

=============
![image](https://user-images.githubusercontent.com/6008084/123224555-8c3cd000-d4ef-11eb-9d7a-9ddcd1bc60b9.png)

**Comment by saivineeth100** [comment]
You can copy code in form1 class and paste in your Form1 class
It works fine
Provided add Change button click event of your button to button1_Click in example code

**Comment by saivineeth100** [comment]
You can copy code in form1 class and paste in your Form1 class
It works fine
Provided add Change button click event of your button to button1_Click in example code

**Comment by sanketgroup** [comment]
pls see attached video. (this is not Net.Core) (This is on .Net Framework)

https://user-images.githubusercontent.com/6008084/123231811-2a339900-d4f6-11eb-8a2c-b20dc8466747.mp4

**Comment by saivineeth100** [comment]
There were some unmerged commits in .net Framework
Now fetch latest repo from github and build it will work

**Comment by sanketgroup** [comment]
1. I downloaded your new repo and built new DLL, copied that new dll to my existing project. But the error is same as shown in video.
2. I downloaded your new repo, opened TallyConnector-NetFramework.sln. Built sucessfully. But when I open "WinFormsExample.sln" and try to build I get following error.
====================
![image](https://user-images.githubusercontent.com/6008084/123242240-73d4b180-d4ff-11eb-8e60-b93eeb50271d.png)

**Comment by saivineeth100** [comment]
Send me your anydesk ID at contact@saivineeth.com
