### ISSUE TITLE
How to insert a Sales Voucher

### ISSUE THREAD

**Issue by chiranstha** [Accounting-Companion/TallyConnector#20]
can not work in salesvoucher

**Comment by saivineeth100** [comment]
not work means what is not working?
You need to be more specific with what error you are getting along with the code you used
and steps to reproduce the same

You can refer [this test](https://github.com/Accounting-Companion/TallyConnector/blob/5cb7e0c8724f36416fd802a72ae0378d30dc7ed1/Tests/Converters/XMLConverterHelpers/CommonTests.cs#L110) where I can create a Sales Voucher with Inventory
