### ISSUE TITLE
Need to add Additionl Discription in sales voucher Item description

### ISSUE THREAD

**Issue by Thiyaguar** [Accounting-Companion/TallyConnector#22]
HI,

I need 4 additional description to be added in item details when creating sales vouchers.

**Comment by saivineeth100** [comment]
Explain your requirement in more detail.
like expected output, sample xml ..etc

**Comment by saivineeth100** [comment]
References - [Enabling feature](https://help.tallysolutions.com/tally-prime/sales-process/print-sales-invoice-with-additional-details/#:~:text=Enable%20the%20option%20to%20add%20description,invoice%20until%20you%20disable%20the%20option)
Screenshot - 
<img width="1280" alt="temp" src="https://user-images.githubusercontent.com/64919520/223319477-1aaf6e1d-3985-4931-9921-5d7fb16d6e02.png">
XML - 
```
....
      <ALLINVENTORYENTRIES.LIST>
       <BASICUSERDESCRIPTION.LIST TYPE="String">
        <BASICUSERDESCRIPTION>Krishna</BASICUSERDESCRIPTION>
        <BASICUSERDESCRIPTION>Dxgfg</BASICUSERDESCRIPTION>
       </BASICUSERDESCRIPTION.LIST>
       <STOCKITEMNAME>CDROM Disks 10s</STOCKITEMNAME>
....
      </ALLINVENTORYENTRIES.LIST>
....
```
