### ISSUE TITLE
Tallyprime edit log

### ISSUE THREAD

**Issue by sunilsoni761** [Accounting-Companion/TallyConnector#25]
I’m using tally prime edit log this api some functions not working like i fatch company but address and field recived null in voucher i fatch list in voucher ledger ledger id null recived

**Comment by saivineeth100** [comment]
post the code you are using.
so that I can reproduce the error

**Comment by sunilsoni761** [comment]
I have attach latest nugget library latest version i think tallyprime edit log is different

**Comment by saivineeth100** [comment]
> I have attach latest nugget library latest version i think tallyprime edit log is different

In order work on this ,
I require more context of error and Steps to reproduce error
