### ISSUE TITLE
tally Class Accessing from tallyconnector

### ISSUE THREAD

**Issue by Aruntechlogica** [Accounting-Companion/TallyConnector#26]
![ttt](https://user-images.githubusercontent.com/129924252/234504495-816edaad-06b6-4e79-933b-0728167980db.png)

  public Tally Ctally = new Tally();

tally class is not found in the tallyconnector library can u please explain the how to take data from tallyprime by using ur code.
can u please give u r contact number

**Comment by saivineeth100** [comment]
Tally class was there previously and renamed to [Tally Service](https://github.com/Accounting-Companion/TallyConnector/blob/master/src/TallyConnector/Services/TallyService/TallyService.cs)

**Comment by Aruntechlogica** [comment]
thanks
