### ISSUE TITLE
Error While GetVouchersAsync

### ISSUE THREAD

**Issue by dhirajdewani** [Accounting-Companion/TallyConnector#27]
TallyConnector.Core.Exceptions.TallyXMLParsingException: 'There is an error in XML document (5403, 51). - <GSTDUTYHEAD TYPE="String">CGST</GSTDUTYHEAD>'

InvalidOperationException: Instance validation error: 'CGST' is not a valid value for GSTTaxType.

**Comment by saivineeth100** [comment]
> TallyConnector.Core.Exceptions.TallyXMLParsingException: 'There is an error in XML document (5403, 51). - CGST'
> 
> InvalidOperationException: Instance validation error: 'CGST' is not a valid value for GSTTaxType.

This is an issue with Tally Prime 3 release, apart from this there are other breaking changes,
I am working on it
