### ISSUE TITLE
Exception in Getting GetLedgersAsync

### ISSUE THREAD

**Issue by dhirajdewani** [Accounting-Companion/TallyConnector#28]
Inner Exception 1:
InvalidOperationException: There is an error in XML document (68047, 85).

Inner Exception 2:
InvalidOperationException: Instance validation error: 'Unregistered/Consumer' is not a valid value for GSTRegistrationType.

**Comment by saivineeth100** [comment]
@dhirajdewani v2.0.17 fixes this
