### ISSUE TITLE
Getting all voucher for particular Ledger

### ISSUE THREAD

**Issue by sanketgroup** [Accounting-Companion/TallyConnector#3]
Hello
Is it possible to get all vouchers of a particular ledger for a particular period?
(similar to what we do in Tally bt going Display > Account Books > Ledger)

**Comment by saivineeth100** [comment]
Yes you can
but no specific method for that one 
You need to use GetNativeCollectionXML method  and send custom filter

**Edit:** Sending custom Filter didn't worked
we need change collection type to 'Vouchers : Ledger' and <Childof>'ledgername'</Childof>

**Comment by saivineeth100** [comment]
~~Added option to get ledger vouchers and group vouchers based on name and period~~
 
~~//Display > Account Books > Ledger
List<Voucher> Vouchers = await TTally.GetLedgerVouchers("Sales - Exports", null, "01-Mar-2010");
//Display > Account Books > Group Vouchers
List<Voucher> Vouchers = await TTally.GetGroupVouchers("Local Sales", null, "01-oct-2016");~~

Removed above method as it is not required here,
 **But Still we can get ledger vouchers by using following method** 

```c#
     string xml = await GetNativeCollectionXML(rName: "Vouchers", colType: "Vouchers : Ledger", Sv: sv,childof:ledgerName,
                                                      NativeFields: Nativelist);

     List<Voucher> Vouchers = GetObjfromXml<VoucherEnvelope>(xml).Body.Data.Collection.Vouchers;
```

**Comment by ShareefKadalayi** [comment]
Hi Bro,
How to get Ledger Vouchers with running total..?

**Comment by saivineeth100** [comment]
we don't support out of the box all reports.
but you can extend tally connector as per your needs.
For Ex: We already fetching [master stats report ](https://github.com/Accounting-Companion/TallyConnector/blob/master/src/TallyConnector/Services/TallyService/GeneralReports.cs#L4)in default Tally Connector
