### ISSUE TITLE
Get Vouchers by  VoucherType

### ISSUE THREAD

**Issue by mdowais** [Accounting-Companion/TallyConnector#31]
Hello, I am trying to get Vouchers by Type. 

I am able to get All Vouchers, but how do i filter them by type example get all Sales Voucher?

And, is it possible to export a Sale Voucher as PDF?

**Comment by saivineeth100** [comment]
we can send filters to GetVouchersMethod,
 If you want only sales vouchers 
 ```c#
 var vchs = await _tallyService.GetVouchersAsync<Voucher>(new PaginatedRequestOptions()
 {
     Filters = new List<Filter>() { new("TC_SalesFilter","$$IsSales:$VoucherTypeName") }    
 });
 ```
