### ISSUE TITLE
Get Vouchers based on ledger

### ISSUE THREAD

**Issue by dhruvahuja2301** [Accounting-Companion/TallyConnector#32]
Is there a way to get all the vouchers for a time period for a ledger using python?

I am able to get all ledgers, but i am not able to find how to put a specific ledger in filter for GetVouchersAsync function

**Comment by saivineeth100** [comment]
This library support filtering vouchers based on Date.
Ex : [VoucherTest](https://github.com/Accounting-Companion/TallyConnector/blob/master/src/Tests/Services/TallyService/TallyObjects/VoucherTests.cs#L15)

As of now we didn't added support to get voucher's based on Ledger (I am planning to add them in future for fetching vouchers based on ledger,stockitem ..etc.,)

For now, you can use filters. supported by this library.
```c#
var vchs = await _tallyService.GetVouchersAsync<Voucher>(new RequestOptions()
            {
                FromDate = new(2022, 4, 1),
               ToDate = new(2023 3, 31),
                Filters = new List<Filter>() { new("TC_VCHLEDGFILTER","$PartyName =LedgName") }               
            });
```

**Comment by dhruvahuja2301** [comment]
I tried calling the function but getting error 

```TypeError: No method matches given arguments for TallyService.GetVouchersAsync: (<class 'TallyConnector.Core.Models.RequestOptions'>)```

below is my code


```reqoptions = RequestOptions()
reqoptions.FromDate=DateTime(2023,4,1)
reqoptions.ToDate=DateTime(2024,3,31)
print(reqoptions.FromDate)
print(reqoptions.ToDate)
reqoptions.Filter = List[Filter]()
reqoptions.Filter.Add(Filter("TC_VCHLEDGFILTER","PartyName ="+LedgName))

print(tally.GetVouchersAsync(reqoptions).Result)
```

**Comment by saivineeth100** [comment]
you are using which version of tallyconnector?

**Comment by dhruvahuja2301** [comment]
I had picked the latest one from here https://github.com/saivineeth100/Python_Tally/tree/main

**Comment by saivineeth100** [comment]
Change code to 
```tally.GetVouchersAsync[Voucher](reqoptions).Result```
and update the lib folder, pushed new files now

**Comment by dhruvahuja2301** [comment]
Yes, i am getting a list of vouchers, but i believe that filter is not working properly, I am getting all the vouchers irrespective of ledgers from the date 1st april 2023

Suppose my party name is ABCD
how should i add the filter part 

Filter("TC_VCHLEDGFILTER","PartyName = ABCD"))

like this?

**Comment by dhruvahuja2301** [comment]
Below code works (python) but it doesn't give list of inventories

```
reqoptions.Filters = List[Filter]()
reqoptions.Filters.Add(Filter("TC_VCHLEDGFILTER","$PartyName=ABCD EFGH"))
```

**Comment by dhruvahuja2301** [comment]
you can close this issue, i am getting the vouchers for specific ledger. Thanks

**Comment by dhruvahuja2301** [comment]
Is there another filter to get the purchase and receipt details to for a specific ledger?

**Comment by saivineeth100** [comment]
> Below code works (python) but it doesn't give list of inventories
> 
> ```
> reqoptions.Filters = List[Filter]()
> reqoptions.Filters.Add(Filter("TC_VCHLEDGFILTER","$PartyName=ABCD EFGH"))
> ```

There fetch list property in request option mention what you want there ,
For EX: refer -[This FetchList](https://github.com/Accounting-Companion/TallyConnector/blob/master/src/TallyConnector.Core/Models/Constants.cs#L69)
Also refer [tests  ](https://github.com/Accounting-Companion/TallyConnector/blob/master/src/Tests/Services/TallyService/TallyObjects/VoucherTests.cs)even though its in c#, concept is same

**Comment by saivineeth100** [comment]
> Is there another filter to get the purchase and receipt details to for a specific ledger?

Purchase will be there in purchase vouchers so you need to filter based on property vouchertypename
Ex : reqoptions.Filters.Add(Filter("TC_VCHTYPEFILTER","$vouchertypename={Constants.VoucherType.PurchaseVoucherType }"))

**Comment by saivineeth100** [comment]
Also create a new issue for every new query and since you are using python create an issue [here ](https://github.com/saivineeth100/Python_Tally/)
