### ISSUE TITLE
Requesting to add support for sorting by field on PagniatedRequests

### ISSUE THREAD

**Issue by samsylvestertty** [Accounting-Companion/TallyConnector#36]
Is there an option to retrieve Paginated objects with sort? I tried searching for the Paginated request in the list of properties and in code but couldn't find an object for sort. I can fetch records and sort with the result but I would like to have the sort in paginated result.

Please close if the capability already exists. 

Thank you

**Comment by saivineeth100** [comment]
Since TDL does not support Paginated requests 
I Implemented pagination myself using line Index, which allocated Line Index based on default sort.

If we use pagination and use custom sort it messes up with pagination.
So, if we want Custom sort from Tally then we need to remove pagination.

**Comment by samsylvestertty** [comment]
Understood. My usecase is to process data from tally. If it is GUID sorted I can read Invoices before receipts and payments. 
Could you please share the xml tag in the api that is responsible for sorting? I tried using SORT tag under collection but doesn't seem to work. 
Thanks again for your response.

**Comment by saivineeth100** [comment]
If sort is in collection that is used as source collection sort will not work

Also, it needs to be like this.
Collection.Sort =[ "@@Default :$GUID"]

this is how it will be in TDL
<img width="596" alt="image" src="https://github.com/Accounting-Companion/TallyConnector/assets/64919520/b1865d4c-b13e-4d72-942a-864f6989d0a8">

**Comment by samsylvestertty** [comment]
Thanks again for your prompt response. I don't have much knowledge on TDL. 

Is this from your code?
Collection.Sort =[ "@@default :$GUID"]. IF yes, can I use it in PaginatedRequestionOptions?

Out of topic question: Is there a way to read Deleted Vouchers? I tried $IsDeleted = Yes in the Filters collection. Didn't work

**Comment by saivineeth100** [comment]
no,
In options I didn't provided sort
but you can create your implementation and set that property for collection.

Deleted vouchers are not saved in Tally unless you use Edit log
if you are using Edit log and need deleted vouchers you need to Extend Collection class and add property 
IncludeDeleted and set to Yes

**Comment by samsylvestertty** [comment]
Thank you. Understood introduction of sort might affect the common functionality. Closing the issue.
