### ISSUE TITLE
Get only those Vouchers or Ledgers that were altered or created between a certain Date Range

### ISSUE THREAD

**Issue by aquib-sh** [Accounting-Companion/TallyConnector#37]
First of all I would like to Thank You for this library and looking forward to contribute into it. I had a question regarding it's usage.

Is it possible to get only those Vouchers, Ledgers, Units etc that were modified or created between a certain date?

**Background**: I have fetched all the tables from Tally and saved it into a database and now the second time I only want to get the values that were created or altered after I uploaded those tables so that I avoid manual heavy comparison on the database and only get the data that is needed.

> Suppose I have two DateTime X and Y 
> Where,
> 
> X = 6th July 2023 
> Y = 1st January 2024
> 
> **Objective**: To Get only those vouchers or ledgers that were altered or created between X and Y and if possible also know what fields were changed. 

In Tally there is something called EditLog that I saw.  Is it something that can be accessed via this library or we have to use some other way to get the Objective?

**Comment by saivineeth100** [comment]
As of now Edit log support is not there but will added in v3 can be tracked [here](https://github.com/Accounting-Companion/TallyConnector/tree/Feature_TDLReportSourceGen)

but if you are using Edit log you can use below code to get only records that are altered or created after nth date
Ex: if you want records after 21-jan-2024
```csharp
PaginatedRequestOptions options = new()
{
    Filters = new() { new("TC_CreatedorAlteredAfterDateFilter", "($CREATEDDATE >= $$Date:21-01-2024) or ($ALTEREDON >= $$Date:21-01-2024)") }
};
var resp = await _tallyService.GetVouchersAsync(options);
```
If you want in date Range, you can use "and" and mention the Max date in Formulae.
```
($CREATEDDATE >= $$Date:21-01-2024) and ($CREATEDDATE < $$Date:01-02-2024)
```

if you are not using Editlog then filter will be based on AlterId
when synvcing for first time make a call to GetLastAlterIdsAsync () and save in db
when need to sync incrementally 
add filter like below.
```csharp
PaginatedRequestOptions options = new()
{
    Filters = new() { new("TC_CreatedorAlteredAfterDateFilter", "($AlterId > 202)") }
};
var resp = await _tallyService.GetVouchersAsync(options);
```


I think Tally prime Edit Log has some data on fields changed in case of alter scenario. but I still didn't explored that.
