### ISSUE TITLE
[Question] Identifying the "Paid from" account in payment or "Paid to" account in receipt 

### ISSUE THREAD

**Issue by samsylvestertty** [Accounting-Companion/TallyConnector#39]
Is there a way to find the Paid from in a payment voucher or Paid to in a receipt voucher?
I checked the xml response generated with the payload you construct but couldn't find on relevant to this

Need to identify the marked ledger from the list of LedgerEntry collection from Tally

![image](https://github.com/Accounting-Companion/TallyConnector/assets/29976793/c3146b7c-3d05-4cd8-b8ec-044cddea10f5)

Sorry if this is handled differently already. Please guide

**Comment by saivineeth100** [comment]
any ledger details will be there in voucher.Ledgers or voucher.InventoryAllocations[].Ledgers
you can find bank ledger also there

**Comment by samsylvestertty** [comment]
Thank you @saivineeth100 , I could see the HDFC Bank Account in the list of ledgers. But is there a flag that specifies **HDFC Bank Account** is the ledger from which amount is paid from?
I tried filtering amount greater than or lesser than but as you can see in the screenshot there are data entered with negative value which screws up the filter
Thanks again for the help :)

**Comment by saivineeth100** [comment]
The entry itself is wrong
How it will be negative 

If we are receiving an amount then it will be a receipt voucher, we cannot use payment and use a negative amount 

In general 
For payment vouchers, bank accounts will be credited means will be positive
For receipt vouchers , bank accounts will be debited means positive
You can filter based on that or directly use voucher.PartyLedger as it will bank ledger

**Comment by samsylvestertty** [comment]
I understand, but the data we have, has such scenario. I just raised this issue to understand if we have any flag that identifies the bank account apart from filtering by amount. 

Closing the issue. 

Thanks again

**Comment by saivineeth100** [comment]
By default there is no such fiield,
But you can extend ledgerEntry class and add new property 
Ex: 
public class CustLedgerEntry:LedgerEntry{

public bool IsPaymentLedger  {get;set;}
}
While sending request add compute 
"IsPaymentLedger  :$IsCashBankAccount:Ledger:$LedgerName"
