### ISSUE TITLE
I was unable to export the daybook data for the specific time period.

### ISSUE THREAD

**Issue by ghost** [Accounting-Companion/TallyConnector#40]
Below is the XML request that I am sending.
Version: Tally prime 
###
<ENVELOPE>
    <HEADER>
        <VERSION>1</VERSION>
        <TALLYREQUEST>Export</TALLYREQUEST>
        <TYPE>Data</TYPE>
        <ID>DayBook</ID>
    </HEADER>
    <BODY>
        <DESC>
            <STATICVARIABLES>
                <SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
                 <SVFROMDATE TYPE="DATE">1-Apr-2023</SVFROMDATE>
                 <SVTODATE TYPE="DATE">23-Jan-2024</SVTODATE>
            </STATICVARIABLES>
        </DESC>
    </BODY>
</ENVELOPE>

##

![Uploading image.png…]()

**Comment by saivineeth100** [comment]
There is no xml , 
What is the error?
