### ISSUE TITLE
Stock item quantity is always turning into positive.

### ISSUE THREAD

**Issue by parassanghani6** [Accounting-Companion/TallyConnector#42]
In my Tally Prime, I have a stock item quantity that is negative (-22 PCS). When utilizing GetStockItemAsync to get stock items, OpeningBal.Number is consistently returned as an absolute value (22).

Like any value which is negative, in response turning into positive.
ex. 
-18 => 18
-2  => 2

**Comment by saivineeth100** [comment]
In general stock will not have negative balance,
but will fix that

**Comment by parassanghani6** [comment]
That obvious, stock never get negative but we have situation where it fall into negative. 

Thank you for consideration.
