### ISSUE TITLE
Getting Stock Vouchers

### ISSUE THREAD

**Issue by sanketgroup** [Accounting-Companion/TallyConnector#9]
How can I get Stock Vouchers?

for e.g Item Name is: "Aasam Tea 5kg"

I want to get all stock vouchers of this selected Item.
To get this in Tally, we go to "Stock Summary" > then Enter on in Item > It will show all the transactions for a particular stock item.

How can I get this via XML in this vb.net Application?
Thanks

**Comment by saivineeth100** [comment]
Added new method
```c#
            await TTally.Check();
            List<Voucher> Vouchers = await TTally.GetInventoryVouchers("Aasam Tea 5kg");
```
This will get all inventory Vouchers

**Comment by sanketgroup** [comment]
This is not returning QTY and Value of the voucher.
Like what it shows in "Inward" and "Outwards" columns in Tally Stock Vouchers.

**Comment by saivineeth100** [comment]
You need Vouchers or Stock Summary
**If Vouchers** 
Qty and value of transaction is present in Inventory allocations for sales ledger
**If Stock Summary**
I didn't want to add support for static reports in this library
But you can use existing API to fetch Static report XML and convert to object

**Comment by sanketgroup** [comment]
Essentially I am looking as following:
![2021-07-14_21-52-22](https://user-images.githubusercontent.com/6008084/125658185-32bbda89-bded-492a-87e3-cf5b95488d73.jpg)

**Comment by saivineeth100** [comment]
So you want Stock Vouchers Summary (Report name is Stock Vouchers)
[Use this XML](https://documenter.getpostman.com/view/13855108/TzeRpAMt#84464ff8-3dfc-4718-85ce-61bc33081e13)

All Tally XMLS are[ here](https://documenter.getpostman.com/view/13855108/TzeRpAMt)

**Comment by sanketgroup** [comment]
yes, correct. That one is working.
Issue is, it does not return Voucher Number.

**Comment by saivineeth100** [comment]
It is returning 
check `<DSPEXPLVCHNUMBER>` tag

This report shows everything that is shown in Stock Vouchers report

**Comment by sanketgroup** [comment]
I do not find any such tag <DSPEXPLVCHNUMBER> in response.

I am sending following request.
```

<?xml version="1.0" encoding="UTF-8"?>
<ENVELOPE>
   <HEADER>
      <VERSION>1</VERSION>
      <TALLYREQUEST>Export</TALLYREQUEST>
      <TYPE>Data</TYPE>
      <ID>Stock Vouchers</ID>
   </HEADER>
   <BODY>
      <DESC>
         <STATICVARIABLES>
            <EXPLODEFLAG>No</EXPLODEFLAG>
            <SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
             <SVFROMDATE TYPE='Date'>1-4-21</SVFROMDATE>
          <SVTODATE TYPE='Date'>31-3-22</SVTODATE>
            <StockItemName>Aasam Tea 5 kg</StockItemName>
         </STATICVARIABLES>
      </DESC>
   </BODY>
</ENVELOPE>
```

**Comment by saivineeth100** [comment]
> I do not find any such tag in response.
> 
> I am sending following request.
> 
> ```
> 
> <?xml version="1.0" encoding="UTF-8"?>
> <ENVELOPE>
>    <HEADER>
>       <VERSION>1</VERSION>
>       <TALLYREQUEST>Export</TALLYREQUEST>
>       <TYPE>Data</TYPE>
>       <ID>Stock Vouchers</ID>
>    </HEADER>
>    <BODY>
>       <DESC>
>          <STATICVARIABLES>
>             <EXPLODEFLAG>No</EXPLODEFLAG>
>             <SVEXPORTFORMAT>$$SysName:XML</SVEXPORTFORMAT>
>              <SVFROMDATE TYPE='Date'>1-4-21</SVFROMDATE>
>           <SVTODATE TYPE='Date'>31-3-22</SVTODATE>
>             <StockItemName>Aasam Tea 5 kg</StockItemName>
>          </STATICVARIABLES>
>       </DESC>
>    </BODY>
> </ENVELOPE>
> ```

You should see that tag in response for me it is coming

**Comment by sanketgroup** [comment]
when i send request, I get only following response.
```

<ENVELOPE>
    <DSPVCHDATE>16-4-2021</DSPVCHDATE>
    <DSPVCHITEMACCOUNT>PRASHANT MEHTA 359244</DSPVCHITEMACCOUNT>
    <DSPVCHTYPE>Sale</DSPVCHTYPE>
    <DSPINBLOCK>
        <DSPVCHINQTY></DSPVCHINQTY>
        <DSPVCHINAMT></DSPVCHINAMT>
    </DSPINBLOCK>
    <DSPOUTBLOCK>
        <DSPVCHOUTQTY>1 Pcs</DSPVCHOUTQTY>
        <DSPVCHNETTOUTAMT>23046.88</DSPVCHNETTOUTAMT>
    </DSPOUTBLOCK>
    <DSPCLBLOCK>
        <DSPVCHCLQTY></DSPVCHCLQTY>
        <DSPVCHCLAMT></DSPVCHCLAMT>
    </DSPCLBLOCK>
    <DSPVCHDATE>16-4-2021</DSPVCHDATE>
    <DSPVCHITEMACCOUNT>PRASHANT MEHTA 359244</DSPVCHITEMACCOUNT>
    <DSPVCHTYPE>Sale</DSPVCHTYPE>
    <DSPINBLOCK>
        <DSPVCHINQTY></DSPVCHINQTY>
        <DSPVCHINAMT></DSPVCHINAMT>
    </DSPINBLOCK>
    <DSPOUTBLOCK>
        <DSPVCHOUTQTY>1 Pcs</DSPVCHOUTQTY>
        <DSPVCHNETTOUTAMT>23437.50</DSPVCHNETTOUTAMT>
    </DSPOUTBLOCK>
    <DSPCLBLOCK>
        <DSPVCHCLQTY>0 Pcs</DSPVCHCLQTY>
        <DSPVCHCLAMT></DSPVCHCLAMT>
    </DSPCLBLOCK>
  </ENVELOPE>
```

**Comment by sanketgroup** [comment]
Ok, I found temporary solution.

If you fresh start the Tally and try to get response, it does not include <DSPEXPLVCHNUMBER>.

I manually Exported XML by doing "Alt+E" from Tally, 
And then tried to send Request from Postman, with same code,  now it is returning <DSPEXPLVCHNUMBER>

It includes this tag in reponse till I keep Tally open.
If I restart Tally, then it will again stop senidng this Tag, so again I have to atleast one time manually run Export command in Tally GUI (any export will resolve the issue) and then send a request from Postman.

This is weird behavior.
Do you face same issue? Please Restart Tally, do not export anything from Tally GUI, and send command from Postman.
It will respond without Voucher Number Tag.

**Comment by saivineeth100** [comment]
> Ok, I found temporary solution.
> 
> If you fresh start the Tally and try to get response, it does not include .
> 
> I manually Exported XML by doing "Alt+E" from Tally,
> And then tried to send Request from Postman, with same code, now it is returning
> 
> It includes this tag in reponse till I keep Tally open.
> If I restart Tally, then it will again stop senidng this Tag, so again I have to atleast one time manually run Export command in Tally GUI (any export will resolve the issue) and then send a request from Postman.
> 
> This is weird behavior.
> Do you face same issue? Please Restart Tally, do not export anything from Tally GUI, and send command from Postman.
> It will respond without Voucher Number Tag.


Ok I understood
I tried exporting and compare with xml response may be that is the reason i am getting voucher number
**Solution**
Add 
`<ExplodeVNum>Yes</ExplodeVNum>`
in Static variables
I updated [XML](https://documenter.getpostman.com/view/13855108/TzeRpAMt#84464ff8-3dfc-4718-85ce-61bc33081e13)

**Note:**
This is not weird behavior
 when exporting reporting  using GUI  ExplodeVNum(Show Voucher no in Export Config) is set to yes
To set that in XML request  we need to send ExplodeVNum tag (Same as what we do for explode tag)

**Comment by sanketgroup** [comment]
It is working perfectly after adding that line.
Thanks
